name: SCA Praiyder Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Praiyder SCA
      uses: praiyder/praiyder-action@v1
      with:
        api-key: ${{ secrets.PRAIYDER_API_KEY }}
